### ISSUE TITLE
Application exit

### ISSUE THREAD

**Issue by Phuket2** [controversial/Image2ASCII-iOS#4]
have a way to exit the application without having to know 2  finger swipe down

**Comment by controversial** [comment]
Sure. I'll work on this. Right now I'm doing history homework, I'll work on this in an hour or so.

**Comment by Phuket2** [comment]
Lol, take it easy. It's just a note/to do list, when you have time or if you think you even want to do it.

**Comment by The-Penultimate-Defenestrator** [comment]
No, I think it's a good idea :)

**Comment by controversial** [comment]
No, I think it's a good idea.

**Comment by controversial** [comment]
Fixed!
