### ISSUE TITLE
Color input in  export image box requires hex

### ISSUE THREAD

**Issue by Phuket2** [controversial/Image2ASCII-iOS#6]
The input box could have a label indicating that a hex value is required, or better still be able to use rgb / rgba values and or color names
I think if you try to set a color of a ui object with an invalid string it goes to white it think.
Also, I haven't checked the code, but I think you do the major processing and then try and use the color. I would be better checked first to see if the background color is valid.

**Comment by controversial** [comment]
I'll put a note about how hex values are required. It would be  more sensible than allowing users to type in RGB tuples to present a color picking dialog, eventually.

I don't think any major processing is done before the color. I think it stores the text of the ASCII art, then the first thing it does is create a new PIL image of that color, before it draws the text onto it. But all the major processing is done before the background image is actually changed. 

The way to avoid this would be to have a clear image with text, and then change background color behind it. Then when render and export is selected, actually create the image.

**Comment by Phuket2** [comment]
But for the color, look at this simple code...

```
import ui

# not a good way but relying on pythonista parser
# to make a color
def color_check(the_colour):
    temp = ui.Button()
    temp.background_color = the_colour
    return temp.background_color

if __name__ == '__main__':
    print color_check((255, 0, 0, .9))
    print color_check((0,255,0))
    print color_check('yellow')
    print color_check('#915c83')
    print color_check('#915c')
    print color_check('crapyyyyyyyy')

But it works. Does not fail. I would not sat the best, but it's ok!
```

**Comment by controversial** [comment]
Fixed your formatting for you. But also, only the last 4 examples would work, because the text box returns a string.

**Comment by controversial** [comment]
Closed. I pass values through ImageColor now.
